version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass secret1nw0rldpa55
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master